name: Deploy Worker
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.2.4
              with:
                version: 8

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install

            - name: deploy-worker
              uses: drivly/deploy-worker@beta-3
              with:
                  name: "cdn"
                  main: "./src/index.ts"
                  config: "wrangler.toml"
                  cloudflareAccountId: ${{ secrets.CF_ACCOUNT_ID }}
                  cloudflareApiToken: ${{ secrets.CF_API_TOKEN }}
